/*$$$LICENCE_NORDIC_STANDARD<2023>$$$*/

#ifndef NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__
#define NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifndef NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE
#define NRFX_INTERCONNECT_APB_LOCAL_DPPI_DEFINE
#endif

#define NRFX_INTERCONNECT_APB_LOCAL_BUSES_PROP {}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_APB_HALTIUM_CELLCORE_H__
