###############################################################################
#  CPU & BOARD info
#

ARCH_SET("RISC-V")

set(STARTUP_FILE "gcc_startup_nrf54l10_flpr.S")
set(SYSTEM_FILE "system_nrf54l.c")

set(NORDIC_DEVICE "NRF54L10_XXAA")
set(NORDIC_DOMAIN "NRF_FLPR")

set(FLAG_RISCV_ARCH "rv32emc_zicsr")
set(FLAG_RISCV_ABI  "ilp32e")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0007D000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x00082800)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x20020000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x10000)
endif()

set(FLASHING_COMMAND nrfjprog --family NRF54L --sectorerase --verify --program)
set(RESETTING_COMMAND nrfjprog --family NRF54L --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_VPR_CLIC
  NRFX_TEST_API_CHECK_NRF_VPR_CSR
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VEVIF
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VIO
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VTIM
  NRFX_TEST_ON_TARGET_NRF_VPR
  NRFX_TEST_ON_TARGET_NRF_VPR_CLIC
  NRFX_TEST_ON_TARGET_NRF_VPR_CLIC_TIMER
  NRFX_TEST_ON_TARGET_NRF_VPR_PREEMTION
  NRFX_TEST_ON_TARGET_NRF_VPR_TRAP_ECALL
  NRFX_TEST_ON_TARGET_NRF_VPR_TRAP_FAULT
  NRFX_TEST_ON_TARGET_NRF_VPR_VIO
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE_TIMER
  NRFX_TEST_ON_TARGET_NRFX_GRTC_MAIN
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_VEVIF
  )
