###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf5340_network.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf5340_network.s")
endif()

set(SYSTEM_FILE "system_nrf5340_network.c")

set(NORDIC_DEVICE "NRF5340_XXAA")
set(NORDIC_DOMAIN "NRF_NETWORK")

set(FLAG_CORE "cortex-m33")
set(FLAG_FPU  "soft")

set(FLASH_START_ADDR 0x01000000)
set(FLASH_SIZE       0x100000)
set(RAM_START_ADDR   0x21000200)
set(RAM_SIZE         0xfe00)

set(FLASHING_COMMAND nrfjprog --coprocessor CP_NETWORK --sectorerase --program)
set(RESETTING_COMMAND nrfjprog --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_CCM
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_DCNF
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_ECB
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_IPC
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_RESET
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VMC
  NRFX_TEST_API_CHECK_NRF_VREQCTRL
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_IDS
  NRFX_TEST_API_CHECK_NRFX_IPC
  NRFX_TEST_API_CHECK_NRFX_POWER
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RNG
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  NRFX_TEST_EXAMPLE_REGISTER_RETENTION
  NRFX_TEST_EXAMPLE_TEMP
  NRFX_TEST_EXAMPLE_UARTE
  NRFX_TEST_EXAMPLE_WDT
  NRFX_TEST_ON_TARGET_NRFX_CLOCK
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_LFXO
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_DPPIC
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE_TIMER
  NRFX_TEST_ON_TARGET_NRFX_GPPI
  NRFX_TEST_ON_TARGET_NRFX_IDS_NET
  NRFX_TEST_ON_TARGET_NRFX_IPC_NET
  NRFX_TEST_ON_TARGET_NRFX_NVMC
  NRFX_TEST_ON_TARGET_NRFX_POWER
  NRFX_TEST_ON_TARGET_NRFX_RNG
  NRFX_TEST_ON_TARGET_NRFX_RTC
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TEMP
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TIMER_GPPI
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_WDT
  NRFX_TEST_UNIT_NRFX_PRS
  )
