###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf54h20_radiocore.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf54h20_radiocore.s")
endif()

set(SYSTEM_FILE "system_nrf54h.c")
set(SVD_FILE    "nrf54h20_radiocore.svd")

set(NORDIC_DEVICE "NRF54H20_XXAA")
set(NORDIC_DOMAIN "NRF_RADIOCORE")

set(FLAG_CORE "cortex-m33")

if (NOT FLAG_FPU)
#TODO: change when HM-14894 is fixed
  set(FLAG_FPU  "soft")
endif()

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0E066000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x40000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x23000000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x8000)
endif()

if (NOT UICR_ADDRESS)
  set(UICR_ADDRESS     0xFFFA000)
endif()

set(FLASHING_COMMAND echo "Not supported - HALTIUM targets work only on PALLADIUM emulator")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_BELLBOARD
  NRFX_TEST_API_CHECK_NRF_CACHE
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_EXMIF
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_HSFLL
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_LRCCONF
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MPC
  NRFX_TEST_API_CHECK_NRF_MVDMA
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_RAMC
  NRFX_TEST_API_CHECK_NRF_RESETINFO
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TBM
  NRFX_TEST_API_CHECK_NRF_TDDCONF
  NRFX_TEST_API_CHECK_NRF_TDM
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_UICR
  NRFX_TEST_API_CHECK_NRF_USBHS
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_IDS
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TBM
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_BELLBOARD
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_API_CHECK_NRFY_TBM
  NRFX_TEST_EXAMPLE_BELLBOARD_REMOTE
  NRFX_TEST_EXAMPLE_BELLBOARD_SEC_NETWORK
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_GRTC
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_INTERDOMAIN_DPPI_NETWORK
  NRFX_TEST_EXAMPLE_JENKINS_XML
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  NRFX_TEST_EXAMPLE_MVDMA
  NRFX_TEST_EXAMPLE_SOFTWARE_RESET
  NRFX_TEST_ON_TARGET_NRF_CACHE
  NRFX_TEST_ON_TARGET_NRFX_BELLBOARD_NET
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_DPPIC
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_GPPI
  NRFX_TEST_ON_TARGET_NRFX_GRTC_MAIN
  NRFX_TEST_ON_TARGET_NRFX_IDS_NET
  NRFX_TEST_ON_TARGET_NRFX_MVDMA
  NRFX_TEST_ON_TARGET_NRFX_PPIB
  NRFX_TEST_ON_TARGET_NRFX_PRS
  NRFX_TEST_ON_TARGET_NRFX_PWM
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SPIM_EXT
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_WDT
  NRFX_TEST_UNIT_NRFX_MVDMA
  NRFX_TEST_UNIT_NRFX_PRS
  )
