###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf52.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf52.s")
endif()

set(SYSTEM_FILE "system_nrf52.c")

set(NORDIC_DEVICE "NRF52832_XXAA")

set(FLAG_CORE "cortex-m4")
set(FLAG_FPU  "hard")

set(FLASH_START_ADDR 0x0)
set(FLASH_SIZE       0x80000)
set(RAM_START_ADDR   0x20000200)
set(RAM_SIZE         0xfe00)

set(FLASHING_COMMAND nrfjprog --sectorerase --program)
set(RESETTING_COMMAND nrfjprog --pinreset)

list(APPEND APP_SPECIFIC_DEFINES "NRF52_ERRATA_58_ENABLE_WORKAROUND=1")

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_BPROT
  NRFX_TEST_API_CHECK_NRF_CCM
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_ECB
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_MWU
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_QDEC
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_I2S
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_POWER
  NRFX_TEST_API_CHECK_NRFX_PPI
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RNG
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPI
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWI
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UART
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_EXAMPLE_FTPAN183_GENERATOR
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  NRFX_TEST_EXAMPLE_REGISTER_RETENTION
  NRFX_TEST_EXAMPLE_SAADC_ADV_CONT_IRQ
  NRFX_TEST_EXAMPLE_SAADC_HIGH_FREQUENCY
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_BLOCKING
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_IRQ
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_MULTICHANNEL_BLOCKING
  NRFX_TEST_EXAMPLE_TEMP
  NRFX_TEST_EXAMPLE_UART
  NRFX_TEST_EXAMPLE_UARTE
  NRFX_TEST_EXAMPLE_WDT
  NRFX_TEST_ON_TARGET_NRF_TEST_STRESS
  NRFX_TEST_ON_TARGET_NRF_FPU
  NRFX_TEST_ON_TARGET_NRF_GPIO
  NRFX_TEST_ON_TARGET_NRFX_CLOCK
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_LFXO
  NRFX_TEST_ON_TARGET_NRFX_COMP
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE_TIMER
  NRFX_TEST_ON_TARGET_NRFX_GPPI
  NRFX_TEST_ON_TARGET_NRFX_I2S
  NRFX_TEST_ON_TARGET_NRFX_LPCOMP
  NRFX_TEST_ON_TARGET_NRFX_NFCT
  NRFX_TEST_ON_TARGET_NRFX_NVMC
  NRFX_TEST_ON_TARGET_NRFX_PDM
  NRFX_TEST_ON_TARGET_NRFX_POWER
  NRFX_TEST_ON_TARGET_NRFX_PPI
  NRFX_TEST_ON_TARGET_NRFX_PRS
  NRFX_TEST_ON_TARGET_NRFX_PWM
  NRFX_TEST_ON_TARGET_NRFX_QDEC
  NRFX_TEST_ON_TARGET_NRFX_RNG
  NRFX_TEST_ON_TARGET_NRFX_RTC
  NRFX_TEST_ON_TARGET_NRFX_SAADC
  NRFX_TEST_ON_TARGET_NRFX_SPI
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SPIS
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TEMP
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TIMER_GPPI
  NRFX_TEST_ON_TARGET_NRFX_TWI
  NRFX_TEST_ON_TARGET_NRFX_TWI_CONT
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_TWIS
  NRFX_TEST_ON_TARGET_NRFX_UART
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_WDT
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_COMP_DAC
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_LPCOMP_DAC
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_SAADC_DAC
  NRFX_TEST_UNIT_NRFX_COMP
  NRFX_TEST_UNIT_NRFX_EGU
  NRFX_TEST_UNIT_NRFX_FLAG32_ALLOCATOR
  NRFX_TEST_UNIT_NRFX_GPIOTE
  NRFX_TEST_UNIT_NRFX_I2S
  NRFX_TEST_UNIT_NRFX_LPCOMP
  NRFX_TEST_UNIT_NRFX_PDM
  NRFX_TEST_UNIT_NRFX_PPI
  NRFX_TEST_UNIT_NRFX_PRS
  NRFX_TEST_UNIT_NRFX_PWM
  NRFX_TEST_UNIT_NRFX_QDEC
  NRFX_TEST_UNIT_NRFX_RNG
  NRFX_TEST_UNIT_NRFX_RTC
  NRFX_TEST_UNIT_NRFX_SAADC
  NRFX_TEST_UNIT_NRFX_SPI
  NRFX_TEST_UNIT_NRFX_SPIM
  NRFX_TEST_UNIT_NRFX_SPIS
  NRFX_TEST_UNIT_NRFX_SYSTICK
  NRFX_TEST_UNIT_NRFX_TEMP
  NRFX_TEST_UNIT_NRFX_TIMER
  NRFX_TEST_UNIT_NRFX_TWI
  NRFX_TEST_UNIT_NRFX_TWIM
  NRFX_TEST_UNIT_NRFX_TWIS
  NRFX_TEST_UNIT_NRFX_UART
  NRFX_TEST_UNIT_NRFX_WDT
  )
