###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf9230_engb_cellcore.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf9230_engb_cellcore.s")
endif()

set(SYSTEM_FILE "system_nrf92.c")
set(SVD_FILE    "nrf9230_engb_cellcore.svd")

set(NORDIC_DEVICE "NRF9230_ENGB_XXAA")
set(NORDIC_DOMAIN "NRF_CELLCORE")

set(FLAG_CORE "cortex-m33")

if (NOT FLAG_FPU)
  set(FLAG_FPU  "hard")
endif()

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0E066000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x400000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x24000000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x80000)
endif()

set(FLASHING_COMMAND echo "Not supported - HALTIUM targets work only on PALLADIUM emulator")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_BELLBOARD
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_EXMIF
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_LRCCONF
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MPC
  NRFX_TEST_API_CHECK_NRF_MVDMA
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_RAMC
  NRFX_TEST_API_CHECK_NRF_RESETINFO
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TBM
  NRFX_TEST_API_CHECK_NRF_TDDCONF
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_UICR
  NRFX_TEST_API_CHECK_NRF_USBHS
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_I2S
  NRFX_TEST_API_CHECK_NRFX_IDS
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_MVDMA
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TBM
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_BELLBOARD
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_API_CHECK_NRFY_TBM
  NRFX_TEST_EXAMPLE_EMPTY
  )
