###############################################################################
#  CPU & BOARD info
#

ARCH_SET("RISC-V")

set(STARTUP_FILE "gcc_startup_nrf9220_sysctrl.S") 
set(SYSTEM_FILE "system_nrf92.c")

set(NORDIC_DEVICE "NRF9220_XXAA")
set(NORDIC_DOMAIN "NRF_SYSCTRL")

set(FLAG_RISCV_ARCH "rv32emc_zicsr")
set(FLAG_RISCV_ABI  "ilp32e")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0xE080000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x20000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x2F880000) 
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x10000)
endif()

set(FLASHING_COMMAND echo "Not supported - HALTIUM targets work only on PALLADIUM emulator")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_FLL16M
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRCCONF
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_HFXO64M
  NRFX_TEST_API_CHECK_NRF_HSFLL
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_LFCLOCKMUX
  NRFX_TEST_API_CHECK_NRF_LFRC
  NRFX_TEST_API_CHECK_NRF_LFXO
  NRFX_TEST_API_CHECK_NRF_LRCCONF
  NRFX_TEST_API_CHECK_NRF_MBIAS
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MRAMC
  NRFX_TEST_API_CHECK_NRF_OSCRFR
  NRFX_TEST_API_CHECK_NRF_OTPC
  NRFX_TEST_API_CHECK_NRF_PCRM
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_RAMC
  NRFX_TEST_API_CHECK_NRF_RESETINFO
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SWEXT
  NRFX_TEST_API_CHECK_NRF_TDDCONF
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VDET1v0
  NRFX_TEST_API_CHECK_NRF_VDETAO0v8
  NRFX_TEST_API_CHECK_NRF_VDETAO1v8
  NRFX_TEST_API_CHECK_NRF_VDETIO
  NRFX_TEST_API_CHECK_NRF_VDETPOF5v0
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_VPR_CLIC
  NRFX_TEST_API_CHECK_NRF_VPR_CSR
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VEVIF
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VIO
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VTIM
  NRFX_TEST_API_CHECK_NRF_VREGAO0v8
  NRFX_TEST_API_CHECK_NRF_VREGMRAM
  NRFX_TEST_API_CHECK_NRF_VREGSU
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_MVDMA
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_GPIO
  )
