###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf9120.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf9120.s")
endif()

set(SYSTEM_FILE "system_nrf91.c")

set(NORDIC_DEVICE "NRF9120_XXAA")
set(NORDIC_DOMAIN "NRF_APPLICATION")

set(FLAG_CORE "cortex-m33")
set(FLAG_FPU  "hard")

set(FLASH_START_ADDR 0x0)
set(FLASH_SIZE       0x100000)
set(RAM_START_ADDR   0x20000200)
set(RAM_SIZE         0x3fe00)

set(FLASHING_COMMAND nrfjprog --sectorerase --program)
set(RESETTING_COMMAND nrfjprog --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_IPC
  NRFX_TEST_API_CHECK_NRF_KMU
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_REGULATORS
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VMC
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_I2S
  NRFX_TEST_API_CHECK_NRFX_IPC
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_POWER
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_ON_TARGET_NRF_VMC
  NRFX_TEST_ON_TARGET_NRFX_CLOCK
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_LFXO
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_DPPIC
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_I2S
  NRFX_TEST_ON_TARGET_NRFX_NVMC
  NRFX_TEST_ON_TARGET_NRFX_PDM
  NRFX_TEST_ON_TARGET_NRFX_POWER
  NRFX_TEST_ON_TARGET_NRFX_PWM
  NRFX_TEST_ON_TARGET_NRFX_RTC
  NRFX_TEST_ON_TARGET_NRFX_SAADC
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_WDT
  )
