###############################################################################
#  CPU & BOARD info
#

list(APPEND C_DEFINES            BOARD_FPGA NRF_SKIP_CLOCK_CONFIGURATION NRF_SKIP_TAMPC_SETUP NRF_CONFIG_NFCT_PINS_AS_GPIOS)
list(APPEND APP_SPECIFIC_DEFINES BOARD_FPGA NRF_SKIP_CLOCK_CONFIGURATION NRF_SKIP_TAMPC_SETUP NRF_CONFIG_NFCT_PINS_AS_GPIOS)
