###############################################################################
#  CPU & BOARD info
#

list(APPEND C_DEFINES             NRF_SKIP_TAMPC_SETUP NRF_DISABLE_FICR_TRIMCNF NRF_SKIP_GLITCHDETECTOR_DISABLE NRF_CONFIG_NFCT_PINS_AS_GPIOS NRF_SKIP_CLOCK_CONFIGURATION)
list(APPEND APP_SPECIFIC_DEFINES  NRF_SKIP_TAMPC_SETUP NRF_DISABLE_FICR_TRIMCNF NRF_SKIP_GLITCHDETECTOR_DISABLE NRF_CONFIG_NFCT_PINS_AS_GPIOS NRF_SKIP_CLOCK_CONFIGURATION)

set(RTL_SIM 1)
set(SIM_ARGS +FW2TB_PRINT_ON_NEWLINE)

macro(GENERATE_SIM_CMD)
    set(SIM_COMMAND sudo docker run -v ${CMAKE_CURRENT_BINARY_DIR}:/sim/duta -v ${CMAKE_CURRENT_BINARY_DIR}:/sim/out -it docker-dtr.nordicsemi.no/sig/${SIM_DOCKER} runsim ${SIM_ARGS} +PROGRAM_A1=${TARGET_NAME}.elf)
endmacro()
