/*$$$LICENCE_NORDIC_STANDARD<2022>$$$*/

#ifndef NRFX_INTERCONNECT_IPCT_HALTIUM_SECURE_H__
#define NRFX_INTERCONNECT_IPCT_HALTIUM_SECURE_H__

#ifdef __cplusplus
extern "C" {
#endif

#if ((NRFX_IPCTx_PUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM() | \
     NRFX_IPCTx_SUB_CONFIG_ALLOWED_CHANNELS_MASK_BY_INST_NUM()) > \
     NRFX_BIT_MASK(LOCAL_IPCT_NUM))
#error "Invalid mask for IPCT subscibe/publish defined."
#endif

#ifndef NRFX_INTERCONNECT_IPCT_LOCAL_DEFINE
#define NRFX_INTERCONNECT_IPCT_LOCAL_DEFINE NRFX_IPCT_CHANNELS_ENTRY();
#endif // NRFX_INTERCONNECT_IPCT_LOCAL_DEFINE

#define NRFX_INTERCONNECT_IPCT_LOCAL_IPCT_PROP \
{                                              \
    NRFX_INTERCONNECT_IPCT_PROP_ENTRY()        \
}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_IPCT_HALTIUM_SECURE_H__
