/*$$$LICENCE_NORDIC_STANDARD<2022>$$$*/

#ifndef NRFX_INTERCONNECT_IPCT_HALTIUM_PPR_H__
#define NRFX_INTERCONNECT_IPCT_HALTIUM_PPR_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifndef NRFX_INTERCONNECT_IPCT_LOCAL_DEFINE
#define NRFX_INTERCONNECT_IPCT_LOCAL_DEFINE
#endif

#define NRFX_INTERCONNECT_IPCT_LOCAL_IPCT_PROP {}

#ifdef __cplusplus
}
#endif

#endif // NRFX_INTERCONNECT_IPCT_HALTIUM_PPR_H__
