###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf54l05_application.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf54l05_application.s")
endif()

set(SYSTEM_FILE "system_nrf54l.c")
set(SVD_FILE    "nrf54l05_application.svd")

set(NORDIC_DEVICE "NRF54L05_XXAA")
set(NORDIC_DOMAIN "NRF_APPLICATION")

set(FLAG_CORE "cortex-m33")

if (NOT FLAG_FPU)
    set(FLAG_FPU  "hard")
endif()

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x00000000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x40000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x20000000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x10000)
endif()

if (NOT UICR_ADDRESS)
  set(UICR_ADDRESS     0x00FFE000)
endif()

set(FLASHING_COMMAND nrfjprog --family NRF54L --sectorerase --verify --program)
set(RESETTING_COMMAND nrfjprog --family NRF54L --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_CACHE
  NRFX_TEST_API_CHECK_NRF_CCM
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_CRACEN
  NRFX_TEST_API_CHECK_NRF_CRACEN_CM
  NRFX_TEST_API_CHECK_NRF_CRACEN_RNG
  NRFX_TEST_API_CHECK_NRF_CTRLAP
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_GLITCHDET
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_KMU
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MPC
  NRFX_TEST_API_CHECK_NRF_OSCILLATORS
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_REGULATORS
  NRFX_TEST_API_CHECK_NRF_RESET
  NRFX_TEST_API_CHECK_NRF_RRAMC
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TAMPC
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_CRACEN
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RRAMC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_EXAMPLE_PPR_LAUNCHER
  NRFX_TEST_ON_TARGET_NRF_CACHE
  NRFX_TEST_ON_TARGET_NRF_FPU
  NRFX_TEST_ON_TARGET_NRF_GPIO
  NRFX_TEST_ON_TARGET_NRFX_CLOCK
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_LFXO
  NRFX_TEST_ON_TARGET_NRFX_COMP
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_CRACEN
  NRFX_TEST_ON_TARGET_NRFX_DPPIC
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_EMPTY
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE_TIMER
  NRFX_TEST_ON_TARGET_NRFX_GPPI
  NRFX_TEST_ON_TARGET_NRFX_GPPI_EGU
  NRFX_TEST_ON_TARGET_NRFX_GRTC_MAIN
  NRFX_TEST_ON_TARGET_NRFX_GRTC_MAIN_LFXO
  NRFX_TEST_ON_TARGET_NRFX_I2S
  NRFX_TEST_ON_TARGET_NRFX_LPCOMP
  NRFX_TEST_ON_TARGET_NRFX_PDM
  NRFX_TEST_ON_TARGET_NRFX_POWER
  NRFX_TEST_ON_TARGET_NRFX_PPIB
  NRFX_TEST_ON_TARGET_NRFX_PRS
  NRFX_TEST_ON_TARGET_NRFX_PWM
  NRFX_TEST_ON_TARGET_NRFX_QDEC
  NRFX_TEST_ON_TARGET_NRFX_RRAMC
  NRFX_TEST_ON_TARGET_NRFX_SAADC
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SPIM_64MHZ
  NRFX_TEST_ON_TARGET_NRFX_SPIM_EXT
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TEMP
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TIMER_64MHZ
  NRFX_TEST_ON_TARGET_NRFX_TIMER_GPPI
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_UARTE_64MHZ
  NRFX_TEST_ON_TARGET_NRFX_WDT
  )
