###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf5340_application.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf5340_application.s")
endif()

set(SYSTEM_FILE "system_nrf5340_application.c")

set(NORDIC_DEVICE "NRF5340_XXAA")
set(NORDIC_DOMAIN "NRF_APPLICATION")

set(FLAG_CORE "cortex-m33")
set(FLAG_FPU  "hard")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE 0x100000)
endif()

set(RAM_START_ADDR 0x20000200)
set(RAM_SIZE       0x3fe00)

set(FLASHING_COMMAND nrfjprog --coprocessor CP_APPLICATION --sectorerase --program)
set(FLASHING_QSPI_COMMAND nrfjprog --coprocessor CP_APPLICATION --qspisectorerase --program)
set(RESETTING_COMMAND nrfjprog --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_BOARD_SPECIFIC_PCA10095_MAP_UARTE_GPIOS_TO_NET
  NRFX_TEST_API_CHECK_NRF_CACHE
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_DCNF
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_FPU
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_IPC
  NRFX_TEST_API_CHECK_NRF_KMU
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_OSCILLATORS
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_QDEC
  NRFX_TEST_API_CHECK_NRF_REGULATORS
  NRFX_TEST_API_CHECK_NRF_RESET
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VMC
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_I2S
  NRFX_TEST_API_CHECK_NRFX_IDS
  NRFX_TEST_API_CHECK_NRFX_IPC
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_POWER
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_QSPI
  NRFX_TEST_API_CHECK_NRFX_RAM_CTRL
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_USBD
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_EXAMPLE_FTPAN183_GENERATOR
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_FPU
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  NRFX_TEST_EXAMPLE_QSPI_DOUBLE_BUFFERING
  NRFX_TEST_EXAMPLE_QSPI_MCU_STUCK_GENERATOR
  NRFX_TEST_EXAMPLE_REGISTER_RETENTION
  NRFX_TEST_EXAMPLE_SAADC_ADV_CONT_IRQ
  NRFX_TEST_EXAMPLE_SAADC_HIGH_FREQUENCY
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_BLOCKING
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_IRQ
  NRFX_TEST_EXAMPLE_SAADC_SIMPLE_MULTICHANNEL_BLOCKING
  NRFX_TEST_EXAMPLE_SPIM_EXT
  NRFX_TEST_EXAMPLE_UARTE
  NRFX_TEST_EXAMPLE_USBD_HID
  NRFX_TEST_EXAMPLE_WDT
  NRFX_TEST_ON_TARGET_NRF_TEST_STRESS
  NRFX_TEST_ON_TARGET_NRF_CACHE
  NRFX_TEST_ON_TARGET_NRF_FPU
  NRFX_TEST_ON_TARGET_NRFX_CLOCK
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_LFXO
  NRFX_TEST_ON_TARGET_NRFX_CLOCK_TIMER
  NRFX_TEST_ON_TARGET_NRFX_COMP
  NRFX_TEST_ON_TARGET_NRFX_COREDEP
  NRFX_TEST_ON_TARGET_NRFX_DPPIC
  NRFX_TEST_ON_TARGET_NRFX_EGU
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE
  NRFX_TEST_ON_TARGET_NRFX_GPIOTE_TIMER
  NRFX_TEST_ON_TARGET_NRFX_GPPI
  NRFX_TEST_ON_TARGET_NRFX_I2S
  NRFX_TEST_ON_TARGET_NRFX_IDS_APP
  NRFX_TEST_ON_TARGET_NRFX_IPC_APP
  NRFX_TEST_ON_TARGET_NRFX_LPCOMP
  NRFX_TEST_ON_TARGET_NRFX_NFCT
  NRFX_TEST_ON_TARGET_NRFX_NVMC
  NRFX_TEST_ON_TARGET_NRFX_PDM
  NRFX_TEST_ON_TARGET_NRFX_POWER
  NRFX_TEST_ON_TARGET_NRFX_PWM
  NRFX_TEST_ON_TARGET_NRFX_QDEC
  NRFX_TEST_ON_TARGET_NRFX_QSPI
  NRFX_TEST_ON_TARGET_NRFX_RTC
  NRFX_TEST_ON_TARGET_NRFX_SAADC
  NRFX_TEST_ON_TARGET_NRFX_SPIM
  NRFX_TEST_ON_TARGET_NRFX_SPIM_EXT
  NRFX_TEST_ON_TARGET_NRFX_SYSTICK
  NRFX_TEST_ON_TARGET_NRFX_TIMER
  NRFX_TEST_ON_TARGET_NRFX_TIMER_GPPI
  NRFX_TEST_ON_TARGET_NRFX_TWIM
  NRFX_TEST_ON_TARGET_NRFX_UARTE
  NRFX_TEST_ON_TARGET_NRFX_WDT
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_COMP_DAC
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_LPCOMP_DAC
  NRFX_TEST_ON_TARGET_COMPLEX_NRFX_SAADC_DAC
  NRFX_TEST_UNIT_NRFX_PRS
  NRFX_TEST_UNIT_NRFX_QSPI
  NRFX_TEST_UNIT_NRFX_SPIM
  NRFX_TEST_UNIT_NRFX_SPIM_EXT
  NRFX_TEST_UNIT_NRFX_TWIM
  )
