###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf51.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf51.s")
endif()

set(SYSTEM_FILE "system_nrf51.c")

set(NORDIC_DEVICE "NRF51")
list(APPEND C_DEFINES "NRF51422_XXAC")

set(FLAG_CORE "cortex-m0")
set(FLAG_FPU  "soft")

set(FLASH_START_ADDR 0x0)
set(FLASH_SIZE       0x40000)
set(RAM_START_ADDR   0x20000200)
set(RAM_SIZE         0x7e00)

set(FLASHING_COMMAND nrfjprog --sectorerase --program)
set(RESETTING_COMMAND nrfjprog --pinreset)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_CCM
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_ECB
  NRFX_TEST_API_CHECK_NRF_FICR
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_MPU
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_QDEC
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_ADC
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_POWER
  NRFX_TEST_API_CHECK_NRFX_PPI
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_RNG
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SPI
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWI
  NRFX_TEST_API_CHECK_NRFX_UART
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  NRFX_TEST_EXAMPLE_REGISTER_RETENTION
  NRFX_TEST_EXAMPLE_TEMP
  NRFX_TEST_EXAMPLE_UART
  NRFX_TEST_EXAMPLE_WDT
  NRFX_TEST_UNIT_NRFX_ADC
  NRFX_TEST_UNIT_NRFX_FLAG32_ALLOCATOR
  NRFX_TEST_UNIT_NRFX_GPIOTE
  NRFX_TEST_UNIT_NRFX_LPCOMP
  NRFX_TEST_UNIT_NRFX_PPI
  NRFX_TEST_UNIT_NRFX_PRS
  NRFX_TEST_UNIT_NRFX_QDEC
  NRFX_TEST_UNIT_NRFX_RNG
  NRFX_TEST_UNIT_NRFX_RTC
  NRFX_TEST_UNIT_NRFX_SPI
  NRFX_TEST_UNIT_NRFX_TEMP
  NRFX_TEST_UNIT_NRFX_TIMER
  NRFX_TEST_UNIT_NRFX_TWI
  NRFX_TEST_UNIT_NRFX_UART
  NRFX_TEST_UNIT_NRFX_WDT
  )
