###############################################################################
#  CPU & BOARD info
#

ARCH_SET("ARM Cortex-M")

if(IS_LINKER_TOOLCHAIN)
  set(STARTUP_FILE "gcc_startup_nrf7120_enga_application.S")
elseif(IS_SCATTER_TOOLCHAIN)
  set(STARTUP_FILE "arm_startup_nrf7120_application.s")
endif()

set(SYSTEM_FILE "system_nrf7120_enga.c")
set(SVD_FILE    "nrf7120_application.svd")

set(NORDIC_DEVICE "NRF7120_ENGA_XXAA")
set(NORDIC_DOMAIN "NRF_APPLICATION")

set(FLAG_CORE "cortex-m33")

if (NOT FLAG_FPU)
    set(FLAG_FPU  "hard")
endif()

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x00000000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x2C0000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x20000000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0xE0000)
endif()

if (NOT UICR_ADDRESS)
  set(UICR_ADDRESS     0x00FFD000)
endif()

set(FLASHING_COMMAND echo "No hardware available yet")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_AAR
  NRFX_TEST_API_CHECK_NRF_AUXPLL
  NRFX_TEST_API_CHECK_NRF_BELLBOARD
  NRFX_TEST_API_CHECK_NRF_CACHE
  NRFX_TEST_API_CHECK_NRF_CCM
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_CRACEN
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_ECB
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_GLITCHDET
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_KMU
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MPC
  NRFX_TEST_API_CHECK_NRF_MRAMC
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_QDEC
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_REGULATORS
  NRFX_TEST_API_CHECK_NRF_RESET
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TAMPC
  NRFX_TEST_API_CHECK_NRF_TDM
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_UICR
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_CLOCK
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_QSPI2
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RESET_REASON
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_BELLBOARD
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_ON_TARGET_NRFX_MRAMC
  )
