###############################################################################
#  CPU & BOARD info
#

ARCH_SET("RISC-V")

set(STARTUP_FILE "gcc_startup_nrf7140_sysctrl.S")
set(SYSTEM_FILE "system_nrf71.c")

set(NORDIC_DEVICE "NRF7140_XXAA")
set(NORDIC_DOMAIN "NRF_SYSCTRL")

set(FLAG_RISCV_ARCH "rv32emc_zicsr")
set(FLAG_RISCV_ABI  "ilp32e")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0E3F2000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0xC000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x2F880200)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0xF9A0)
endif()

set(FLASHING_COMMAND echo "Not supported - HALTIUM targets work only on PALLADIUM emulator")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_CLOCK
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_EXMIF
  NRFX_TEST_API_CHECK_NRF_FLL16M
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRCCONF
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_HFXO64M
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_LFCLOCKMUX
  NRFX_TEST_API_CHECK_NRF_LFRC
  NRFX_TEST_API_CHECK_NRF_LFXO
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_LRCCONF
  NRFX_TEST_API_CHECK_NRF_MBIAS
  NRFX_TEST_API_CHECK_NRF_MEMCONF
  NRFX_TEST_API_CHECK_NRF_MRAMC
  NRFX_TEST_API_CHECK_NRF_MVDMA
  NRFX_TEST_API_CHECK_NRF_OSCRFR
  NRFX_TEST_API_CHECK_NRF_OTPC
  NRFX_TEST_API_CHECK_NRF_PCRM
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_POWER
  NRFX_TEST_API_CHECK_NRF_PPIB
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_RAMC
  NRFX_TEST_API_CHECK_NRF_RESETHUB
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SWEXT
  NRFX_TEST_API_CHECK_NRF_TBM
  NRFX_TEST_API_CHECK_NRF_TDDCONF
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_USBHS
  NRFX_TEST_API_CHECK_NRF_VDET1v0
  NRFX_TEST_API_CHECK_NRF_VDETAO0v8
  NRFX_TEST_API_CHECK_NRF_VDETAO1v8
  NRFX_TEST_API_CHECK_NRF_VDETAO5v0
  NRFX_TEST_API_CHECK_NRF_VDETIO
  NRFX_TEST_API_CHECK_NRF_VDETPOF5v0
  NRFX_TEST_API_CHECK_NRF_VDETVS0v8
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_VPR_CLIC
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VEVIF
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VTIM
  NRFX_TEST_API_CHECK_NRF_VREG1v0
  NRFX_TEST_API_CHECK_NRF_VREGAO0v8
  NRFX_TEST_API_CHECK_NRF_VREGAO1v8
  NRFX_TEST_API_CHECK_NRF_VREGMAIN
  NRFX_TEST_API_CHECK_NRF_VREGMRAM
  NRFX_TEST_API_CHECK_NRF_VREGSU
  NRFX_TEST_API_CHECK_NRF_VREGUSB
  NRFX_TEST_API_CHECK_NRF_VREGVS0v8
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_IDS
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_MVDMA
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TBM
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_API_CHECK_NRFY_TBM
  NRFX_TEST_EXAMPLE_EMPTY
  NRFX_TEST_EXAMPLE_HELLO_WORLD
  NRFX_TEST_EXAMPLE_MDK_CHECKER
  )
