###############################################################################
#  CPU & BOARD info
#

ARCH_SET("RISC-V")

set(STARTUP_FILE "gcc_startup_nrf7120_enga_flpr.S")
set(SYSTEM_FILE "system_nrf7120_enga.c")

set(NORDIC_DEVICE "NRF7120_ENGA_XXAA")
set(NORDIC_DOMAIN "NRF_FLPR")

set(FLAG_RISCV_ARCH "rv32emc_zicsr")
set(FLAG_RISCV_ABI  "ilp32e")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x00100000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x00020000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x200E0000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x20000)
endif()

set(FLASHING_COMMAND echo "No hardware available yet")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_CRACEN
  NRFX_TEST_API_CHECK_NRF_CTRLAP
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_ECB
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_MPC
  NRFX_TEST_API_CHECK_NRF_MRAMC
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_QDEC
  NRFX_TEST_API_CHECK_NRF_RADIO
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_SPU
  NRFX_TEST_API_CHECK_NRF_TAMPC
  NRFX_TEST_API_CHECK_NRF_TDM
  NRFX_TEST_API_CHECK_NRF_TEMP
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_VPR_CLIC
  NRFX_TEST_API_CHECK_NRF_VPR_CSR
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VEVIF
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VIO
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VTIM
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_QSPI2
  NRFX_TEST_API_CHECK_NRFX_NFCT
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_QDEC
  )
