###############################################################################
#  CPU & BOARD info
#

ARCH_SET("RISC-V")

set(STARTUP_FILE "gcc_startup_nrf9230_enga_ppr.S")
set(SYSTEM_FILE "system_nrf92.c")

set(NORDIC_DEVICE "NRF9230_ENGA_XXAA")
set(NORDIC_DOMAIN "NRF_PPR")

set(FLAG_RISCV_ARCH "rv32emc_zicsr")
set(FLAG_RISCV_ABI  "ilp32e")

if (NOT FLASH_START_ADDR)
  set(FLASH_START_ADDR 0x0E542000)
endif()

if (NOT FLASH_SIZE)
  set(FLASH_SIZE       0x10000)
endif()

if (NOT RAM_START_ADDR)
  set(RAM_START_ADDR   0x2FC00000)
endif()

if (NOT RAM_SIZE)
  set(RAM_SIZE         0x7000)
endif()

set(FLASHING_COMMAND echo "Not supported - HALTIUM targets work only on PALLADIUM emulator")
set(RESETTING_COMMAND)

# TEST SUPPORT info
set(DEVICE_SUPPORTED_TESTS
  NRFX_TEST_API_CHECK_NRF_DPPI
  NRFX_TEST_API_CHECK_NRF_EGU
  NRFX_TEST_API_CHECK_NRF_EXMIF
  NRFX_TEST_API_CHECK_NRF_GPIO
  NRFX_TEST_API_CHECK_NRF_GPIOTE
  NRFX_TEST_API_CHECK_NRF_GRTC
  NRFX_TEST_API_CHECK_NRF_I2S
  NRFX_TEST_API_CHECK_NRF_IPCT
  NRFX_TEST_API_CHECK_NRF_LPCOMP
  NRFX_TEST_API_CHECK_NRF_MVDMA
  NRFX_TEST_API_CHECK_NRF_PDM
  NRFX_TEST_API_CHECK_NRF_PWM
  NRFX_TEST_API_CHECK_NRF_RAMC
  NRFX_TEST_API_CHECK_NRF_SAADC
  NRFX_TEST_API_CHECK_NRF_SPIM
  NRFX_TEST_API_CHECK_NRF_SPIS
  NRFX_TEST_API_CHECK_NRF_TBM
  NRFX_TEST_API_CHECK_NRF_TDDCONF
  NRFX_TEST_API_CHECK_NRF_TIMER
  NRFX_TEST_API_CHECK_NRF_TWIM
  NRFX_TEST_API_CHECK_NRF_TWIS
  NRFX_TEST_API_CHECK_NRF_UARTE
  NRFX_TEST_API_CHECK_NRF_USBHS
  NRFX_TEST_API_CHECK_NRF_VPR
  NRFX_TEST_API_CHECK_NRF_VPR_CLIC
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VEVIF
  NRFX_TEST_API_CHECK_NRF_VPR_CSR_VTIM
  NRFX_TEST_API_CHECK_NRF_WDT
  NRFX_TEST_API_CHECK_NRFX_COMMON
  NRFX_TEST_API_CHECK_NRFX_COMP
  NRFX_TEST_API_CHECK_NRFX_DPPI
  NRFX_TEST_API_CHECK_NRFX_EGU
  NRFX_TEST_API_CHECK_NRFX_GPIOTE
  NRFX_TEST_API_CHECK_NRFX_GPPI
  NRFX_TEST_API_CHECK_NRFX_I2S
  NRFX_TEST_API_CHECK_NRFX_LPCOMP
  NRFX_TEST_API_CHECK_NRFX_PDM
  NRFX_TEST_API_CHECK_NRFX_PWM
  NRFX_TEST_API_CHECK_NRFX_QDEC
  NRFX_TEST_API_CHECK_NRFX_RTC
  NRFX_TEST_API_CHECK_NRFX_SAADC
  NRFX_TEST_API_CHECK_NRFX_SPIM
  NRFX_TEST_API_CHECK_NRFX_SPIS
  NRFX_TEST_API_CHECK_NRFX_TBM
  NRFX_TEST_API_CHECK_NRFX_TEMP
  NRFX_TEST_API_CHECK_NRFX_TIMER
  NRFX_TEST_API_CHECK_NRFX_TWIM
  NRFX_TEST_API_CHECK_NRFX_TWIS
  NRFX_TEST_API_CHECK_NRFX_UARTE
  NRFX_TEST_API_CHECK_NRFX_WDT
  NRFX_TEST_API_CHECK_NRFY_COMP
  NRFX_TEST_API_CHECK_NRFY_GPIO
  NRFX_TEST_API_CHECK_NRFY_GRTC
  NRFX_TEST_API_CHECK_NRFY_LPCOMP
  NRFX_TEST_API_CHECK_NRFY_QDEC
  NRFX_TEST_API_CHECK_NRFY_TBM
  )
