###############################################################################
#  CPU & BOARD info
#

list(APPEND C_DEFINES            BOARD_FPGA NRF_SKIP_CLOCK_CONFIGURATION NRF_SKIP_TAMPC_SETUP NRF_SKIP_GLITCHDETECTOR_DISABLE)
list(APPEND APP_SPECIFIC_DEFINES BOARD_FPGA NRF_SKIP_CLOCK_CONFIGURATION NRF_SKIP_TAMPC_SETUP NRF_SKIP_GLITCHDETECTOR_DISABLE)
